services:
  - type: web
    name: rendercv-backend
    env: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
