from fastapi import FastAPI, HTTPException, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pydantic import BaseModel
import subprocess
import tempfile
import os
import shutil

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

class ResumeRequest(BaseModel):
    cv: dict

def cleanup_dir(path: str):
    if os.path.exists(path):
        shutil.rmtree(path)

@app.post("/api/generate")
async def generate_resume(request: ResumeRequest, background_tasks: BackgroundTasks):
    import yaml
    
    temp_dir = tempfile.mkdtemp()
    yaml_path = os.path.join(temp_dir, "resume.yaml")
    
    with open(yaml_path, "w") as f:
        yaml.dump({"cv": request.cv}, f, default_flow_style=False)
        
    try:
        subprocess.run(
            ["python3", "-m", "rendercv", "render", yaml_path],
            cwd=temp_dir,
            check=True,
            capture_output=True,
            text=True
        )
        
        import glob
        pdf_files = glob.glob(os.path.join(temp_dir, "rendercv_output", "*.pdf"))
        
        if not pdf_files:
            raise Exception("PDF was not generated by rendercv.")
            
        pdf_path = pdf_files[0]
        
        background_tasks.add_task(cleanup_dir, temp_dir)
        
        return FileResponse(
            path=pdf_path,
            filename="resume.pdf",
            media_type="application/pdf"
        )
        
    except subprocess.CalledProcessError as e:
        cleanup_dir(temp_dir)
        raise HTTPException(status_code=400, detail=f"RenderCV failed: {e.stderr}")
    except Exception as e:
        cleanup_dir(temp_dir)
        raise HTTPException(status_code=500, detail=str(e))
