from fastapi import FastAPI, HTTPException, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pydantic import BaseModel
import subprocess
import tempfile
import os
import shutil

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

class ResumeRequest(BaseModel):
    cv: dict

def cleanup_dir(path: str):
    if os.path.exists(path):
        shutil.rmtree(path)

@app.get("/")
def health_check():
    return {"status": "healthy"}

@app.get("/api/debug")
def debug_env():
    import subprocess
    result = subprocess.run(["pip", "list"], capture_output=True, text=True)
    return {"pip_list": result.stdout}

@app.post("/api/generate")
async def generate_resume(request: ResumeRequest, background_tasks: BackgroundTasks):
    temp_dir = None
    try:
        import json
        
        temp_dir = tempfile.mkdtemp()
        yaml_path = os.path.join(temp_dir, "resume.yaml")
        
        with open(yaml_path, "w") as f:
            json.dump({"cv": request.cv}, f)
            
        subprocess.run(
            ["python3", "-m", "rendercv", "render", yaml_path],
            cwd=temp_dir,
            check=True,
            capture_output=True,
            text=True
        )
        
        import glob
        pdf_files = glob.glob(os.path.join(temp_dir, "rendercv_output", "*.pdf"))
        
        if not pdf_files:
            raise Exception("PDF was not generated by rendercv.")
            
        pdf_path = pdf_files[0]
        
        from fastapi.responses import Response
        with open(pdf_path, "rb") as f:
            pdf_bytes = f.read()
            
        cleanup_dir(temp_dir)
        
        return Response(
            content=pdf_bytes,
            media_type="application/pdf",
            headers={"Content-Disposition": "inline; filename=resume.pdf"}
        )
        
    except subprocess.CalledProcessError as e:
        if temp_dir: cleanup_dir(temp_dir)
        error_msg = e.stderr if e.stderr else e.stdout
        from fastapi.responses import JSONResponse
        return JSONResponse(status_code=400, content={"detail": f"RenderCV Compilation Error:\n{error_msg}"})
    except Exception as e:
        if temp_dir: cleanup_dir(temp_dir)
        import traceback
        from fastapi.responses import JSONResponse
        return JSONResponse(status_code=500, content={"detail": traceback.format_exc()})

from fastapi import UploadFile, File
@app.post("/api/parse")
async def parse_resume(file: UploadFile = File(...)):
    if not os.environ.get("GEMINI_API_KEY"):
        raise HTTPException(status_code=400, detail="GEMINI_API_KEY environment variable is missing on the server.")
    
    temp_dir = tempfile.mkdtemp()
    file_path = os.path.join(temp_dir, file.filename)
    
    try:
        with open(file_path, "wb") as f:
            f.write(await file.read())
            
        from google import genai
        from google.genai import types
        
        client = genai.Client()
        uploaded_file = client.files.upload(file=file_path)
        
        prompt = """
        Extract the resume into this EXACT JSON structure. Only output valid JSON without markdown wrapping.
        {
          "personal": {"name": "", "email": "", "phone": "", "location": ""},
          "socials": [{"network": "LinkedIn", "username": ""}],
          "education": [{"institution": "", "area": "", "degree": "", "start_date": "YYYY-MM", "end_date": "YYYY-MM", "highlights": "Bullet points separated by newlines"}],
          "experience": [{"company": "", "position": "", "location": "", "start_date": "YYYY-MM", "end_date": "YYYY-MM", "highlights": "Bullet points separated by newlines"}],
          "athletics": [{"name": "", "details": ""}]
        }
        """
        
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=[uploaded_file, prompt],
            config=types.GenerateContentConfig(response_mime_type="application/json")
        )
        
        import json
        data = json.loads(response.text)
        cleanup_dir(temp_dir)
        return data
        
    except Exception as e:
        cleanup_dir(temp_dir)
        import traceback
        from fastapi.responses import JSONResponse
        return JSONResponse(status_code=500, content={"detail": traceback.format_exc()})
