from fastapi import FastAPI, HTTPException, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pydantic import BaseModel
import subprocess
import tempfile
import os
import shutil

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

class ResumeRequest(BaseModel):
    cv: dict

def cleanup_dir(path: str):
    if os.path.exists(path):
        shutil.rmtree(path)

@app.get("/")
def health_check():
    return {"status": "healthy"}

@app.get("/api/debug")
def debug_env():
    import subprocess
    result = subprocess.run(["pip", "list"], capture_output=True, text=True)
    return {"pip_list": result.stdout}

@app.post("/api/generate")
async def generate_resume(request: ResumeRequest, background_tasks: BackgroundTasks):
    import yaml
    
    temp_dir = tempfile.mkdtemp()
    yaml_path = os.path.join(temp_dir, "resume.yaml")
    
    with open(yaml_path, "w") as f:
        yaml.dump({"cv": request.cv}, f, default_flow_style=False)
        
    try:
        subprocess.run(
            ["python3", "-m", "rendercv", "render", yaml_path],
            cwd=temp_dir,
            check=True,
            capture_output=True,
            text=True
        )
        
        import glob
        pdf_files = glob.glob(os.path.join(temp_dir, "rendercv_output", "*.pdf"))
        
        if not pdf_files:
            raise Exception("PDF was not generated by rendercv.")
            
        pdf_path = pdf_files[0]
        
        from fastapi.responses import Response
        with open(pdf_path, "rb") as f:
            pdf_bytes = f.read()
            
        cleanup_dir(temp_dir)
        
        return Response(
            content=pdf_bytes,
            media_type="application/pdf",
            headers={"Content-Disposition": "inline; filename=resume.pdf"}
        )
        
    except subprocess.CalledProcessError as e:
        cleanup_dir(temp_dir)
        error_msg = e.stderr if e.stderr else e.stdout
        from fastapi.responses import JSONResponse
        return JSONResponse(status_code=400, content={"detail": f"RenderCV Compilation Error:\n{error_msg}"})
    except Exception as e:
        cleanup_dir(temp_dir)
        import traceback
        from fastapi.responses import JSONResponse
        return JSONResponse(status_code=500, content={"detail": traceback.format_exc()})
